### ISSUE TITLE
Dates are too unspecific

### ISSUE THREAD

**Issue by strogonoff** [ietf-tools/relaton-data-rfcs#4]
According to Relaton model, we expect an ISO 8601 datetime string:

https://github.com/relaton/relaton-models/blob/main/models/DateTime.lutaml#L11

Now that BibXML service is doing some validation, dates in the RFCs source are failing it because they are too unspecific (for example, "2005-03").

Can we add specificity by setting them at least to the first day of the month?

**Comment by ronaldtse** [comment]
> According to Relaton model, we expect an ISO 8601 datetime string:

ISO 8601-2 supports "unspecified" digits:

<img width="563" alt="Screenshot 2022-01-07 at 9 04 54 AM" src="https://user-images.githubusercontent.com/11865/148474524-6eb912cd-bcfb-442d-a46b-9fddc875c9ac.png">

We could use this.

> Can we add specificity by setting them at least to the first day of the month?

That will break the model. We have come across Relaton dates that only have year and cannot be further specified.

**Comment by ronaldtse** [comment]
This is a Relaton issue, moving this to relaton-ietf.

**Comment by rjsparks** [comment]
Closing this per the above.
